export const appState = {
  user: null,
  theme: 'light',
  aktifDers: null,
  aktifFasikul: null,
  aktifKonu: null,
  aktifAltKonu: null,
  currentPage: 1,
  totalPages: 20,
  pdfTotalPages: 20,
  displayTotalPages: 20,
  visiblePages: [],
  zoom: 100,
  drawTool: 'pen',
  drawColor: '#dc2626',
  brushSize: 3,
  testRunning: false,
  timerSec: 0,
  timerInterval: null,
  timerDurationMins: 20,
  timerCountdown: true,
  lastAnswerTime: null,
  timer2minLast: 0,
  altKonuStats: {},
  sorularState: {},
  activeQuestionIdx: 0,
  readingMode: false,
  cevapModalSoruNo: null,
  pdfDocFasikulId: null,
  hatalilar: [
    {ders:'mat',dersAd:'Matematik',konu:'Analitik Düzlem',soruNo:6,tarih:'3 gün önce',yanlisSayisi:2},
    {ders:'fiz',dersAd:'Fizik',konu:'Newton Yasaları',soruNo:2,tarih:'5 gün önce',yanlisSayisi:1},
    {ders:'mat',dersAd:'Matematik',konu:'Analitik Düzlem',soruNo:13,tarih:'1 hafta önce',yanlisSayisi:3}
  ],
  pdfDoc: null,
  drawings: {},
  undoStack: [],
  redoStack: [],
  fabricCanvas: null,
  preferences: {
    sound: true,
    autoNext: true,
    goal: 100,
    timerAlert: true
  },
  cloudIstatistik: null,
  cloudFasikulIstatistik: null,
  cloudSolutionsLoaded: false,
  avatarEmojis: ['🎓','🧑‍🎓','👨‍🎓','👩‍🎓','🦁','🐯','🦊','🦅','🚀','⚡','🔥','🎯','💡','🌟','🏆','🎮','🤖','👾','🧠','🌈'],
  avatarIdx: 0,
  eduDirHandle: null,
  eduDirPermission: 'prompt'
};
